#!/bin/bash

#PBS -N am
#PBS -q fnrdewoody
#PBS -l nodes=1:ppn=20,naccesspolicy=singleuser
#PBS -l walltime=336:00:00
#PBS -m abe
#PBS -M jwillou@purdue.edu

cd $PBS_O_WORKDIR

module load bioinfo
module load java
module load amos/3.1.0
module load MUMmer/4

###following https://bitbucket.org/HeidiLischer/refguideddenovoassembly_pipelines####
cd /scratch/snyder/j/jwillou/pupfish/assembly/

#merge deNovo assembled superblocks into one FASTA file
#for (( j=41; j<=81; j+=10 ))
#do
#	cat  abyssResults/contigs/*_${j}-contigs.fa > abyssResults/${j}_abyssContigs.fa
#done   
#cat abyssResults/*_abyssContigs.fa > abyssResults/abyssContigs.fa
   
#merge Unassembled files
#cat  abyssResults/unassFolder/k*/*-contigs.fa >  abyssResults/unassFolder/Unassembled_Abyss.fa
 
#remove short seq (<500)
#java -jar ./refguided/RemoveShortSeq.jar -i  abyssResults/unassFolder/Unassembled_Abyss.fa -o  abyssResults/Unassembled_Abyss_500.fa -length 500

#merge all files
#cat abyssResults/abyssContigs.fa abyssResults/Unassembled_Abyss_500.fa > abyssResults/deNovo_Superblocks.fa
     
#remove short seq (<200)
#java -jar ./refguided/RemoveShortSeq.jar -i abyssResults/deNovo_Superblocks.fa -o abyssResults/deNovo_Superblocks_200.fa -length 200 -u
 
#remove redundency with AMOScmp
mkdir AMOScmp  
cd AMOScmp
   
#assemble all assembled superblocks with AMOScmp to supercontigs (with the help of reference)
java -jar ../refguided/FastaToAmos.jar -i ../abyssResults/deNovo_Superblocks_200.fa -o deNovo_Superblocks_200_Amos.afg
  
#${progAmos}AMOScmp -D TGT=${superblockSeqAmos} -D REF=${refRed}.fa ${supercontigs}
#run AMPScmp step by step and use multithread nucmer to speed it up

#Building AMOS bank
/group/bioinfo/apps/apps/amos-3.1.0/bin/bank-transact -c -z -b Amos_supercontigs.bnk -m deNovo_Superblocks_200_Amos.afg

#Collecting clear range sequences
/group/bioinfo/apps/apps/amos-3.1.0/bin/dumpreads Amos_supercontigs.bnk > Amos_supercontigs.seq

#Running nucmer
nucmer --maxmatch --threads=20 --prefix=Amos_supercontigs /scratch/snyder/j/jwillou/pupfish/assembly/ref/Cvariegatus_cleaned.fa Amos_supercontigs.seq

#Running layout
/group/bioinfo/apps/apps/amos-3.1.0/bin/casm-layout -t 1000 -U Amos_supercontigs.layout -C Amos_supercontigs.conflict -b Amos_supercontigs.bnk Amos_supercontigs.delta

#Running consensus
/group/bioinfo/apps/apps/amos-3.1.0/bin/make-consensus -o 10 -B -b Amos_supercontigs.bnk

#Outputting contigs
/group/bioinfo/apps/apps/amos-3.1.0/bin/bank2contig Amos_supercontigs.bnk > Amos_supercontigs.contig

#Outputting fasta
/group/bioinfo/apps/apps/amos-3.1.0/bin/bank2fasta -b Amos_supercontigs.bnk > Amos_supercontigs.fasta
