#!/bin/bash

#PBS -N repeats
#PBS -q fnrfish
#PBS -l nodes=1:ppn=10,naccesspolicy=singleuser
#PBS -l walltime=336:00:00
#PBS -m abe
#PBS -M jwillou@purdue.edu

module load bioinfo
module load perl 
module load RepeatMasker/4.0.7 #/group/bioinfo/apps/apps/RepeatMasker-4.0.7
module load RECON/1.08 #/group/bioinfo/apps/apps/RECON-1.08/bin
module load RepeatScout/1.0.5 #/group/bioinfo/apps/apps/RepeatScout-1.0.5
module load nseg/1995-09-28 #/group/bioinfo/apps/apps/nseg-1995-09-28
module load trf/4.04 #/group/bioinfo/apps/apps/trf-4.04
module load rmblast/2.2.28 #/group/bioinfo/apps/apps/blast-2.6.0+/bin

cd /scratch/snyder/j/jwillou/pupfish/assembly/rf_output/repeatmodeler 

#node version did not make library properly(?) so installed separately
#./RepeatModeler-open-1.0.11/BuildDatabase -name pupfish -engine ncbi ../pup_42_k63_scafSeq.fa
#./RepeatModeler-open-1.0.11/RepeatModeler -pa 20 -engine ncbi -database pupfish

#find repeats
#RepeatMasker -pa 20 -e ncbi -lib RM_10887.TueMay141024422019/consensi.fa.classified ../pup_42_k63_scafSeq.fa -dir /scratch/snyder/j/jwillou/pupfish/assembly/rf_output/repeatmodeler/rm_pup
#RepeatMasker -pa 20 -e ncbi -species danio ../pup_42_k63_scafSeq.fa -dir /scratch/snyder/j/jwillou/pupfish/assembly/rf_output/repeatmodeler/rm_danio

#combine de novo and danio repeats found in genome
gunzip rm_danio/pup_42_k63_scafSeq.fa.cat.gz
gunzip rm_pup/pup_42_k63_scafSeq.fa.cat.gz
cat rm_danio/pup_42_k63_scafSeq.fa.cat rm_pup/pup_42_k63_scafSeq.fa.cat > all_pup_mask.cat
ProcessRepeats all_pup_mask.cat

#prep maker input file (isolate complex repeats and reformat)
module load perl/5.26.1
export PERL5LIB=/group/bioinfo/apps/apps/RepeatMasker-4.0.7
perl rmOutToGFF3.pl rm_pup/pup_42_k63_scafSeq.fa.out > pup_42_k63_scafSeq.mask.gff3
grep -v -e "Satellite" -e ")n" -e "-rich" pup_42_k63_scafSeq.mask.gff3 > pup_42_k63_scafSeq.mask.complex.gff3
cat pup_42_k63_scafSeq.mask.complex.gff3 | perl -ane '$id; if(!/^\#/){@F = split(/\t/, $_); chomp $F[-1];$id++; $F[-1] .= "\;ID=$id"; $_ = join("\t", @F)."\n"} print $_' > pup_42_k63_scafSeq.mask.complex.reformat.gff3
