#!/bin/bash

#PBS -N sop
#PBS -q fnrdewoody
#PBS -l nodes=1:ppn=20,naccesspolicy=singleuser
#PBS -l walltime=336:00:00
#PBS -m abe
#PBS -M jwillou@purdue.edu

cd /scratch/snyder/j/jwillou/pupfish/assembly/

module load bioinfo
module load java
module load samtools/1.3
module load bowtie2/2.2.1
module load bamtools/2.3.0
#module load SOAPdenovo/240

###following https://bitbucket.org/HeidiLischer/refguideddenovoassembly_pipelines####
# 7. Step: scaffolding and gap closing

mkdir scaffold_gapClosed
cd scaffold_gapClosed

#write config file
java -jar ../refguided/WriteSoapConfig.jar -insLength 300 -r1 ../R1.fastq -r2 ../R2.fastq -max 151 -ru 2 -rank -o soap.config

#need to download and install SOAP because Snyder version does not have fusion
#https://github.com/aquaskyline/SOAPdenovo2/archive/master.zip <- I downloaded this to my laptop and unzipped
#because I wanted to see what was in the folder, but I guess you could go right to Snyder with wget and tar?
#use 'make' to install (https://github.com/aquaskyline/SOAPdenovo2)
../SOAPdenovo2-master/SOAPdenovo-fusion -D -c ../merged_corr/merged_corrWN_splitFiltered.fa -K 63 -g pup_42_k63 -p 20
../SOAPdenovo2-master/SOAPdenovo-127mer map -s soap.config -g pup_42_k63 -p 20
../SOAPdenovo2-master/SOAPdenovo-127mer scaff -g pup_42_k63 -p 20 -F
   
#remove scaffolds < 200 bp ----------
java -jar ../refguided/RemoveShortSeq.jar -i pup_42_k63.scafSeq -o pup_42_k63_scafSeq.fa -length 200 >> log.txt
java -jar ../refguided/RemoveShortSeq.jar -i pup_42_k63_scafSeq.fa -o pup_42_k63_scafSeq_500.fa -length 500 >> log.txt
java -jar ../refguided/RemoveShortSeq.jar -i pup_42_k63_scafSeq.fa -o pup_42_k63_scafSeq_1000.fa -length 1000 >> log.txt
 
#get statistics
java -jar ../refguided/FastaStats.jar -i pup_42_k63_scafSeq.fa -min 200 >> log.txt
java -jar ../refguided/FastaStats.jar -i pup_42_k63_scafSeq.fa -min 500 >> log.txt
java -jar ../refguided/FastaStats.jar -i pup_42_k63_scafSeq.fa -min 1000 >> log.txt

#map reads against scaffolds
bowtie2-build pup_42_k63_scafSeq.fa pup_42_k63_scafSeq
bowtie2 --sensitive -p 1 -q --phred33 -I 200 -X 500  -x pup_42_k63_scafSeq -1 ../R1.fastq -2 ../R2.fastq| samtools view -bS - | samtools sort - -T pup_42 -o pup_42_all.sorted.bam
samtools index pup_42_all.sorted.bam
bamtools stats -in pup_42_all.sorted.bam >> log.txt

#filter for mapping quality >=10    
samtools view -b -F 4 -q 10 pup_42_all.sorted.bam > pup_42.filtered.sorted.bam
bamtools stats -in pup_42.filtered.sorted.bam >> log.txt
