#!/bin/bash

#PBS -N trimm
#PBS -q fnrfish
#PBS -l nodes=1:ppn=10,naccesspolicy=singleuser
#PBS -l walltime=336:00:00
#PBS -m abe
#PBS -M jwillou@purdue.edu

cd $PBS_O_WORKDIR

module load bioinfo
module load trimmomatic
module load java

cd $PBS_O_WORKDIR

trimmomatic PE -phred33 \
../data/cleaned/040524_WP4-UM_S173_R1_filtered.fastq \
../data/cleaned/040524_WP4-UM_S173_R2_filtered.fastq \
040524_WP4-UM_S173_R1_filteredT.fastq \
040524_WP4-UM_S173_R1_filteredTup.fastq \
040524_WP4-UM_S173_R2_filteredT.fastq \
040524_WP4-UM_S173_R2_filteredTup.fastq \
LEADING:21 TRAILING:20 MINLEN:30 ILLUMINACLIP:trimmomatic_illumina.fa:2:40:10

trimmomatic PE -phred33 \
../data/cleaned/040525_WP2-LM_S174_R1_filtered.fastq \
../data/cleaned/040525_WP2-LM_S174_R2_filtered.fastq \
040525_WP2-LM_S174_R1_filteredT.fastq \
040525_WP2-LM_S174_R1_filteredTup.fastq \
040525_WP2-LM_S174_R2_filteredT.fastq \
040525_WP2-LM_S174_R2_filteredTup.fastq \
LEADING:21 TRAILING:20 MINLEN:30 ILLUMINACLIP:trimmomatic_illumina.fa:2:40:10
